rails_appointment_app/config/routes.rb
Rails.application.routes.draw do
  post 'user_token' => 'user_token#create'
  
  resources :users
  resources :rooms
  resources :appointments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  namespace :api do
    get '/eventbrites' => 'events#index_eventbrites'
  end
  
  mount ActionCable.server => '/cable'
end

rails_appointment_app/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :room

  def start_time_friendly
    start_time.strftime("%A %B %e %Y %l:%M %p")
  end

  def end_time_friendly
    end_time.strftime("%A %B %e %Y %l:%M %p")
  end

end

rails_appointment_app/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if check_schedule && @appointment.save
        appointment_cable(@appointment)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:name, :description, :kind, :start_time, :end_time, :room_id, :user_id)
    end

    def user_appointments
      User.find(appointment_params[:user_id]).appointments
    end

    def room_appointments
      Room.find(appointment_params[:room_id]).appointments
    end

    def intersection_times (new_start, new_end, old_start, old_end )
      return true if (old_start == nil || old_end == nil)
      (new_start <= old_start && new_end <= old_start) || 
      (new_start >= old_end && new_end >= old_end)
    end

    def check_schedule
      check_user_appointments = user_appointments.all? { |appointment| 
        intersection_times(
          @appointment.start_time, 
          @appointment.end_time, 
          appointment.start_time, 
          appointment.end_time
      )}

      check_room_appointments = room_appointments.all? { |appointment| 
        intersection_times(
          @appointment.start_time, 
          @appointment.end_time, 
          appointment.start_time, 
          appointment.end_time
      )}
      puts "check_user_appointments #{check_user_appointments} && check_room_appointments #{check_room_appointments}"

      check_user_appointments && check_room_appointments
    end

    def appointment_cable(appointment)
      ActionCable.server.broadcast(
        "appointment_channel",
        appointment
      )
    end

end

rails_appointment_app/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

rails_appointment_app/app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :appointment_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :appointment_description %>
  </div>

  <div class="field">
    <%= form.label :kind %>
    <%= form.number_field :kind, id: :appointment_type %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :appointment_start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, id: :appointment_end_time %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.number_field :room_id, id: :appointment_room_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :appointment_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails_appointment_app/app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

rails_appointment_app/app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Type</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Room</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.name %></td>
        <td><%= appointment.description %></td>
        <td><%= appointment.kind %></td>
        <td><%= appointment.start_time %></td>
        <td><%= appointment.end_time %></td>
        <td><%= appointment.room_id %></td>
        <td><%= appointment.user_id %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

rails_appointment_app/app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

rails_appointment_app/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @appointment.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @appointment.kind %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @appointment.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @appointment.end_time %>
</p>

<p>
  <strong>Room:</strong>
  <%= @appointment.room_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @appointment.user_id %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>